FROM nginx:1.27-alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html

COPY *.html ./
COPY css/ ./css/
COPY js/ ./js/
COPY icons/ ./icons/

